name: lakehouse_unplugged
version: "1.0.0"
profile: lakehouse_unplugged

models:
  lakehouse_unplugged:
    demo:
      +schema: "demo"
      +materialized: table

    silver:
      +schema: "{{ env_var('DBT_SILVER_SCHEMA', 'silver') }}"
      +on_schema_change: sync_all_columns

      md:
        +materialized: incremental
        +incremental_strategy: merge
        +file_format: iceberg
        +unique_key: kenteken

      rd:
        +materialized: table

    gold:
      +schema: "{{ env_var('DBT_GOLD_SCHEMA', 'gold') }}"
      +on_schema_change: sync_all_columns

      dim:
        +materialized: table

      fact:
        +materialized: incremental
        +incremental_strategy: merge
        +file_format: iceberg
        +unique_key: event_id

    smoke:
      +schema: "{{ env_var('DBT_SMOKE_SCHEMA', 'smoke') }}"
      +materialized: view
