name: lakehouse_unplugged
version: "1.0.0"
profile: lakehouse_unplugged

models:
  lakehouse_unplugged:
    silver:
      +schema: silver
      +on_schema_change: sync_all_columns

      md:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: kenteken

      rd:
        +materialized: table

    gold:
      +schema: gold
      +on_schema_change: sync_all_columns

      dim:
        +materialized: table

      fact:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: event_id

    smoke:
      +schema: "{{ env_var('DBT_SCHEMA', 'dbt_demo') }}"
