lakehouse_unplugged:
  outputs:
    dev:
      type: spark
      method: thrift

      host: "{{ env_var('DBT_SPARK_HOST', 'thrift-server') }}"
      port: 10000

      # Polaris Iceberg catalog + namespace
      catalog: "{{ env_var('DBT_CATALOG', 'polaris') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbt_demo') }}"

      # Geen auth in lokale stack
      auth: NONE
      threads: 4

      # Verbinding / retry-instellingen
      retry_all: false
      connect_retries: 1
      connect_timeout: 10


  target: dev
