lakehouse_unplugged:
  outputs:
    dev:
      type: spark
      method: thrift

      host: "{{ env_var('DBT_SPARK_HOST', 'thrift-server') }}"
      port: "{{ env_var('DBT_SPARK_PORT', '10000') }}"

      # Polaris Iceberg catalog + namespace
      catalog: "{{ env_var('DBT_CATALOG', 'polaris') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbt_demo') }}"

      # Geen auth in lokale stack
      auth: NONE
      threads: 4

      # Verbinding / retry-instellingen
      connect_retries: 5
      connect_timeout: 60
      retry_all: true

  target: dev
