###############################################
# Spark Defaults – Iceberg filesystem (STABIEL)
###############################################

spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.defaultCatalog=spark_catalog
spark.sql.defaultNamespace=default

spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.spark_catalog.type=hadoop
spark.sql.catalog.spark_catalog.warehouse=s3a://warehouse/
spark.scheduler.mode=FAIR

spark.hadoop.fs.s3a.endpoint=http://seaweedfs:8333
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.EnvironmentVariableCredentialsProvider
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.endpoint.region=us-east-1
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem

spark.pyspark.python=/opt/py311/bin/python
spark.pyspark.driver.python=/opt/py311/bin/python
spark.executorEnv.PYSPARK_PYTHON=/opt/py311/bin/python
spark.yarn.appMasterEnv.PYSPARK_PYTHON=/opt/py311/bin/python

spark.executorEnv.AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT=true
spark.driver.extraJavaOptions=-DAWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT=true
spark.executor.extraJavaOptions=-DAWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT=true
